#!/bin/sh
set -eu

case "${1:-}" in
  *Username*) printf '%s\n' 'x-access-token' ;;
  *Password*) printf '%s\n' "${PHARNESS_GIT_PASSWORD:?source reader credential is unavailable}" ;;
  *) exit 1 ;;
esac
