import { useState } from "react";
import { ArrowsClockwise, ChartLineUp, Siren } from "@phosphor-icons/react";
import { EmptyState, ReviewItem } from "../components/Operational";
import { compactId, formatTimestamp, riskTone, statusText } from "../lib/formatters";
import { resourceLabel } from "../lib/resourcePresentation";

type Navigate = (view: string, param?: string) => void;
type IncidentProps = { dashboard: any; selectedId: string | null; openRun: (runId: string) => void; navigate: Navigate };

export function IncidentsView({ dashboard, selectedId, openRun, navigate }: IncidentProps) {
  const incidents = dashboard.data?.incidents ?? [];
  const plans = dashboard.data?.remediationPlans ?? [];
  const selected = incidents.find((incident: any) => incident.id === selectedId) ?? incidents[0] ?? null;
  const linkedPlan = selected ? plans.find((plan: any) => plan.incident_id === selected.id) : null;
  const highSeverity = incidents.filter((incident: any) => ["high", "critical"].includes(incident.severity)).length;
  const candidates = incidents.filter((incident: any) => incident.status === "candidate").length;
  const reasons = selected?.data_json?.reasons;
  const metrics = [["Incidents", String(incidents.length), "latest page"], ["Candidates", String(candidates), "awaiting triage"], ["High severity", String(highSeverity), "operator attention"], ["Run-linked", String(incidents.filter((incident: any) => incident.run_id).length), "execution context"]];
  return <section className="gate-view"><div className="section-heading"><div><h1>Incidents</h1><p>Read-only incident candidates derived from Tekton and Release observability evidence.</p></div><button className="primary-action" type="button" onClick={dashboard.refresh} disabled={dashboard.status === "refreshing"}><ArrowsClockwise size={17} /> {dashboard.status === "refreshing" ? "Refreshing" : "Refresh"}</button></div>
    <div className="summary-grid">{metrics.map(([label, value, note]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div>
    {incidents.length ? <div className="gate-layout"><div className="approval-stack">{incidents.map((incident: any) => <button className={`approval-card ${incident.id === selected?.id ? "is-active" : ""}`} type="button" key={incident.id} onClick={() => navigate("Incidents", incident.id)}><span>{incident.severity} · {statusText(incident.status)}</span><strong>{incident.title}</strong><small>{resourceLabel(incident)} · {compactId(incident.id)}</small><b>{incident.severity}</b></button>)}</div>
      <div className="review-surface"><h2>{selected?.title ?? "Incident"}</h2><p>{selected?.summary ?? "Select an incident to review its evidence."}</p><div className="review-grid"><ReviewItem label="Status" value={statusText(selected?.status)} tone={selected?.status === "candidate" ? "pending" : undefined} /><ReviewItem label="Severity" value={statusText(selected?.severity, "Unknown")} tone={riskTone(selected?.severity) === "high" ? "risk" : "pending"} /><ReviewItem label="Resource" value={resourceLabel(selected)} /><ReviewItem label="Created" value={formatTimestamp(selected?.created_at)} /><ReviewItem label="Observation" value={<button className="link-text" type="button" onClick={() => navigate("Observations", selected?.observation_id)}>{compactId(selected?.observation_id)}</button>} />{linkedPlan ? <ReviewItem label="Remediation plan" value={<button className="link-text" type="button" onClick={() => navigate("Remediation Plans", linkedPlan.id)}>{compactId(linkedPlan.id)}</button>} /> : null}{selected?.run_id ? <ReviewItem label="Run" value={<button className="link-text" type="button" onClick={() => openRun(selected.run_id)}>{compactId(String(selected.run_id))}</button>} /> : null}</div><div className="diff-box"><div><Siren size={18} /> incident evidence</div><pre>{JSON.stringify(Array.isArray(reasons) ? { reasons } : selected?.data_json ?? {}, null, 2)}</pre></div></div>
    </div> : <EmptyState title="No incidents" body="Incident candidates appear when attached Tekton or Release observability evidence needs attention." />}</section>;
}

type RemediationProps = { dashboard: any; selectedId: string | null; navigate: Navigate };

export function RemediationPlansView({ dashboard, selectedId, navigate }: RemediationProps) {
  const plans = dashboard.data?.remediationPlans ?? [];
  const gates = dashboard.data?.approvalGates ?? [];
  const selected = plans.find((plan: any) => plan.id === selectedId) ?? plans[0] ?? null;
  const linkedGates = selected ? gates.filter((gate: any) => gate.remediation_plan_id === selected.id) : [];
  const steps = Array.isArray(selected?.plan_json?.steps) ? selected.plan_json.steps : [];
  const metrics = [["Plans", String(plans.length), "latest page"], ["Drafts", String(plans.filter((plan: any) => plan.status === "draft").length), "awaiting review"], ["Require approval", String(plans.filter((plan: any) => plan.requires_approval).length), "gated execution"], ["High risk", String(plans.filter((plan: any) => ["high", "critical"].includes(plan.risk_level)).length), "operator attention"]];
  return <section className="gate-view"><div className="section-heading"><div><h1>Remediation Plans</h1><p>Read-only remediation drafts. Execution stays behind approval gates; no mutation runs from this view.</p></div><button className="primary-action" type="button" onClick={dashboard.refresh} disabled={dashboard.status === "refreshing"}><ArrowsClockwise size={17} /> {dashboard.status === "refreshing" ? "Refreshing" : "Refresh"}</button></div>
    <div className="summary-grid">{metrics.map(([label, value, note]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div>
    {plans.length ? <div className="gate-layout"><div className="approval-stack">{plans.map((plan: any) => <button className={`approval-card ${plan.id === selected?.id ? "is-active" : ""}`} type="button" key={plan.id} onClick={() => navigate("Remediation Plans", plan.id)}><span>{plan.risk_level} · {statusText(plan.status)}</span><strong>{plan.title}</strong><small>{resourceLabel(plan)} · {compactId(plan.id)}</small><b>{plan.requires_approval ? "gated" : "ungated"}</b></button>)}</div>
      <div className="review-surface"><h2>{selected?.title ?? "Remediation plan"}</h2><p>{selected?.summary ?? "Select a plan to review its steps and gates."}</p><div className="review-grid"><ReviewItem label="Status" value={statusText(selected?.status)} tone={selected?.status === "draft" ? "pending" : undefined} /><ReviewItem label="Risk" value={statusText(selected?.risk_level, "Unknown")} tone={riskTone(selected?.risk_level) === "high" ? "risk" : "pending"} /><ReviewItem label="Requires approval" value={String(selected?.requires_approval ?? false)} /><ReviewItem label="Resource" value={resourceLabel(selected)} /><ReviewItem label="Incident" value={<button className="link-text" type="button" onClick={() => navigate("Incidents", selected?.incident_id)}>{compactId(selected?.incident_id)}</button>} /></div>{steps.length ? <div className="plan-steps">{steps.map((step: any) => <div className="plan-step" key={`${step.order}-${step.capability}`}><b>{step.order}</b><span>{step.kind}</span><strong>{step.capability}</strong><p>{step.summary}</p></div>)}</div> : null}{linkedGates.length ? <div className="resource-chips">{linkedGates.map((gate: any) => <button className={`chip-${gate.status === "pending" ? "pending" : "settled"}`} type="button" key={gate.id} onClick={() => navigate("Approval Gates", gate.id)}>{gate.gate_kind} · {statusText(gate.status)}</button>)}</div> : null}</div>
    </div> : <EmptyState title="No remediation plans" body="Draft remediation plans appear when incident candidates are created from observability evidence." />}</section>;
}

type ObservationProps = { dashboard: any; selectedId: string | null; openRun: (runId: string) => void; navigate: Navigate };

export function ObservationsView({ dashboard, selectedId, openRun, navigate }: ObservationProps) {
  const observations = dashboard.data?.observations ?? [];
  const [sourceFilter, setSourceFilter] = useState("all");
  const sources = ["all", ...new Set(observations.map((observation: any) => observation.source))];
  const filtered = sourceFilter === "all" ? observations : observations.filter((observation: any) => observation.source === sourceFilter);
  const selected = observations.find((observation: any) => observation.id === selectedId) ?? filtered[0] ?? null;
  const metrics = [["Observations", String(observations.length), "latest page"], ["Sources", String(new Set(observations.map((observation: any) => observation.source)).size), "evidence origins"], ["Run-linked", String(observations.filter((observation: any) => observation.run_id).length), "execution context"], ["With artifacts", String(observations.filter((observation: any) => observation.artifact_id).length), "durable payloads"]];
  return <section className="gate-view"><div className="section-heading"><div><h1>Observations</h1><p>Normalized read-only facts persisted from typed cluster reads and control-plane activity.</p></div><div className="detail-actions"><div className="filter-row" role="tablist" aria-label="Observation source filter">{sources.map((option) => <button key={option as string} type="button" className={sourceFilter === option ? "selected" : ""} onClick={() => setSourceFilter(option as string)}>{option as string}</button>)}</div><button className="primary-action" type="button" onClick={dashboard.refresh} disabled={dashboard.status === "refreshing"}><ArrowsClockwise size={17} /> {dashboard.status === "refreshing" ? "Refreshing" : "Refresh"}</button></div></div>
    <div className="summary-grid">{metrics.map(([label, value, note]) => <div className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div>
    {filtered.length ? <div className="gate-layout"><div className="approval-stack">{filtered.map((observation: any) => <button className={`approval-card ${observation.id === selected?.id ? "is-active" : ""}`} type="button" key={observation.id} onClick={() => navigate("Observations", observation.id)}><span>{observation.source} · {observation.kind}</span><strong>{observation.subject}</strong><small>{resourceLabel(observation)} · {compactId(observation.id)}</small><b>{observation.artifact_id ? "artifact" : "inline"}</b></button>)}</div>
      <div className="review-surface"><h2>{selected?.subject ?? "Observation"}</h2><p>{selected?.summary ?? "Select an observation to review its normalized data."}</p><div className="review-grid"><ReviewItem label="Source" value={selected?.source ?? "unknown"} /><ReviewItem label="Kind" value={selected?.kind ?? "unknown"} /><ReviewItem label="Resource" value={resourceLabel(selected)} /><ReviewItem label="Artifact" value={selected?.artifact_id ? compactId(selected.artifact_id) : "none"} />{selected?.run_id ? <ReviewItem label="Run" value={<button className="link-text" type="button" onClick={() => openRun(selected.run_id)}>{compactId(String(selected.run_id))}</button>} /> : null}</div><div className="diff-box"><div><ChartLineUp size={18} /> normalized observation data</div><pre>{JSON.stringify(selected?.data_json ?? {}, null, 2)}</pre></div></div>
    </div> : <EmptyState title="No observations" body="Typed cluster reads and control-plane activity persist observations here." />}</section>;
}
